services:
  - type: web
    name: ecom-api
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./ecom.db
      - key: DEBUG
        value: "False"
      - key: ENVIRONMENT
        value: "production"
      - key: ALGORITHM
        value: "HS256"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"